version: "3.8"
services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: pokeclipse
      POSTGRES_PASSWORD: pokeclipse
      POSTGRES_DB: pokeclipse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
